### ISSUE TITLE
StoreFront, Director and NetScaler Checks Over SSL

### ISSUE THREAD

**Issue by dbretty** [dbretty/EUCMonitoring#20]
Been reported that these checks are not working correctly when using SSL

**Comment by littletoyrobots** [comment]
By changing to the correct port and protocol, it has worked for me.  Perhaps these are self-signed certs?

**Comment by ryancbutler** [comment]
This is probably due to the TLS and self signed certs.  Probably need to put in a check for HTTPS and set PowerShell to use TLS 1.1 or 1.2 and ignore selfsigned.

**Comment by vadgonzalez** [comment]
Still getting errors with Storefront checks. Errors: HTTPSUrl failed
It passes HTTPURL which means URL is correct. Also passing Valid-Cert.
Certificate is wildcard certificate issued by Thawte
anytheaks required in *.json file ?

VERBOSE: Starting Test-Series on Storefront.
VERBOSE: Initializing Results...
VERBOSE: Loading config from euc-monitoring.json
VERBOSE: Loading the configuration for the Storefront series
VERBOSE: Connecting to Server: ctxsfp01.corp.ad
VERBOSE: Connection to ctxsfp01.corp.ad successful
VERBOSE: Series Storefront - Connection Successful to ctxsfp01.corp.ad
VERBOSE: Testing ctxsfp01.corp.ad - Port 80
VERBOSE: Success ctxsfp01.corp.ad - Port 80
VERBOSE: Testing ctxsfp01.corp.ad - Port 443
VERBOSE: Success ctxsfp01.corp.ad - Port 443
VERBOSE: ctxsfp01.corp.ad performing HTTPUrl
VERBOSE: Testing URL: http://ctxsfp01.corp.ad:80/Citrix/PnOGRThinStoreWeb
VERBOSE: Connecting to URL: http://ctxsfp01.corp.ad:80/Citrix/PnOGRThinStoreWeb
VERBOSE: ctxsfp01.corp.ad performing HTTPSUrl
VERBOSE: Testing URL: https://ctxsfp01.corp.ad:443/Citrix/PnOGRThinStoreWeb
VERBOSE: Connecting to URL: https://ctxsfp01.corp.ad:443/Citrix/PnOGRThinStoreWeb
VERBOSE: ctxsfp01.corp.ad performing ValidCert
VERBOSE: Testing Valid Cert on ctxsfp01.corp.ad Port: 443
VERBOSE: ComputerName: ctxsfp01.corp.ad
VERBOSE: State: DEGRADED
VERBOSE: Ports Up: 80 443
VERBOSE: PortsDown:
VERBOSE: ServicesUp:
VERBOSE: ServicesDown:
VERBOSE: ChecksUp: HTTPUrl ValidCert
VERBOSE: ChecksDown: HTTPSUrl
VERBOSE: CheckData:
VERBOSE: Errors: HTTPSUrl failed

**Comment by littletoyrobots** [comment]
Issue was that certs were issued with different fqdn for subject name.  
```
Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."
```
If we temporarily trust all ssl/tls connections for the session, we could get around it, but that's a different can of worms.

**Comment by littletoyrobots** [comment]
Issued confirmed resolved
